# Base configs
baseurl: "https://michaloleszak.com/photography/"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "Photography by Kamila & Michał"
subtitle: "See the world!"
author: "Kamila & Michał"
header:
 title: "Photography"
 subtitle: "by Kamila & Michał"
footer:
 name: "Hey there, we are Kamila & Michał"
 bio: "Kamila is a business intelligence consultant and Michał <a href=\"https://michaloleszak.com\">works in AI</a>, teaching intelligence to machines. Currently based in Warsaw, Poland, we travel the world taking pictures on the way."
 # github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/ramswaroop/photography\">fork me on github</a> ;)"
web_design: "<a href=\"https://github.com/rampatra/photography\">rampatra</a>"
social_urls:
  # facebook: "https://www.facebook.com/ramswaroop"
  twitter: "https://twitter.com/MichalOleszak"
  # instagram: "https://www.instagram.com/ram_patra"
  # dribbble: "https://dribbble.com/rampatra"
  linkedin: "https://www.linkedin.com/in/michal-oleszak/"
  github: "https://github.com/MichalOleszak"
